trigger: none
pool:
  vmImage: "ubuntu-latest"

variables:
- group: LandingZoneVars


jobs:
- job: Deploy
  displayName: Terraform Deploy
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: TerraformInstaller@0
    displayName: Install Terraform latest

  - task: TerraformTaskV2@2
    displayName: 'Terraform : Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/azuredeploy'
      backendServiceArm: 'Shail-Subs(1)(2fae94b1-7a9f-489c-bf7c-877563309b5c)'
      backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
      backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
      backendAzureRmContainerName: '$(backendAzureRmContainerName)'
      backendAzureRmKey: '$(backendAzureRmKey)'

  - task: TerraformTaskV3@3
    displayName: 'Terraform : Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/azuredeploy'
      environmentServiceNameAzureRM: 'Shail-Subs(1)(2fae94b1-7a9f-489c-bf7c-877563309b5c)'

  - task: TerraformTaskV3@3
    displayName: 'Terraform : Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/azuredeploy'
      environmentServiceNameAzureRM: 'Shail-Subs(1)(2fae94b1-7a9f-489c-bf7c-877563309b5c)'

